package com.hsae.bluetoothsdk;
import com.hsae.bluetoothsdk.bean.BluetoothDevice;
import com.hsae.bluetoothsdk.IBluetoothCallback;
interface IBluetoothManager {
    void acceptConnect(int type);
    void acceptPair(String mac, boolean accept);
    void btPowerOff();
    void btPowerOn();
    void connect(String name, String mac);
    void connectA2dp(String mac);
    void connectHfp(String mac);
    void disConnect();
    void disConnectA2dp();
    int getBatteryCharge();
    String getConnectDeviceAddress();
    String getConnectDeviceName();
    int getConnectStatus(int profile);
    String getDeviceName();
    java.util.List<BluetoothDevice> getPairedDevices();
    int getPowerStatus();
    String getSdkVersion();
    int getSignalValue();
    boolean isParing();
    boolean isSearching();
    int pairDevice(String mac, int type);
    boolean registCallback(IBluetoothCallback callback);
    void rejectConnect(int type);
    void rejectPair(String mac, boolean reject);
    int removePair(String mac);
    int search(boolean reserve);
    void setAutoPowerOn(boolean enable);
    void setBtName(String name);
    int stopSearch();
    boolean supportInbandRing();
    boolean supportMusic();
    boolean supportPhone();
    void unBindService();
    boolean unregistCallback(IBluetoothCallback callback);
}
